### ISSUE TITLE
Desktop Swipe Not working

### ISSUE THREAD

**Issue by kurtisyoung** [jerrybendy/vue-touch-events#10]
I've been trying to get the `v-touch:swipe.left="slideNext"` to work on desktop. The swipe event is detect on mobile but not on desktop. I've made sure the disableClick option is set to false.

**Comment by jerrybendy** [comment]
Yes, you're right. Only `tap` event works on desktop.

**Comment by typerory** [comment]
Sweet!

**Comment by leetomblin** [comment]
Is there a way to get swipe events to work on desktop? Other than using responsive design mode, purely for testing, if nothing else.

**Comment by jerrybendy** [comment]
@leetomblin  Yes, there is a workaround to support `swipe` on desktop env: using mouse events instead of touch events, like `mousedown`, `mousemove`, `mouseup`

**Comment by CrucifixArnaud** [comment]
Hello, 

Can you provide a little bit more info about this work around with the actual implementation of the library ? I'm looking in the documentation, but I don't see anything related to that. But maybe it's not available for the moment. 

Thanks

**Comment by Fragilem17** [comment]
I've added a pull request that supports this out of the box.

**Comment by jerrybendy** [comment]
All events (include `swipe`) are supported on both PC and mobile now. You can update version to `^2.0.0` to get this feature.

**Comment by gen4sp** [comment]
@jerrybendy I have 2.2.1 and swipe doesnt work for me on the desktop. Any special setup required?

**Comment by jerrybendy** [comment]
@gen4sp Could you give me an example to show what happened? Just a jsfiddle or codepen link is ok.

**Comment by gen4sp** [comment]
@jerrybendy just v-touch:swipe="swipeHandler(c)" works with touch events and doesn't with mouse ones. Should it work? cant find cdn link for jsfiddle

**Comment by jerrybendy** [comment]
@gen4sp  Is this a problem about swipe tolerance? You can refer #63 to check it

**Comment by gen4sp** [comment]
yes, it is! thank you!

**Comment by gen4sp** [comment]
@jerrybendy oh, no, I've just got it.
I have a small box on the field, and usually when I swipe the mouse down over the box but mouse up out of the box. it seems this is the case. Could it be?

**Comment by jerrybendy** [comment]
@gen4sp Yes, If you release mouse on other elements, the swipe event wouldn't be triggered.

**Comment by bArraxas** [comment]
For me, swipe.left and swipe.right work well on desktop but not on tablet...
