### ISSUE TITLE
vue touch event lost after opening aother component

### ISSUE THREAD

**Issue by tonioseiler** [jerrybendy/vue-touch-events#11]
I have multiple component on one page..
v-touch:swipe works great until I mount another component. After that. the touch listener does not react anymore.
Can I re add the listener somehow?

Regards.

Tonio

**Comment by jerrybendy** [comment]
Do you have an example to show this issue?

**Comment by tonioseiler** [comment]
Look at it here:

http://dev.rotefabrik.ch <http://dev.rotefabrik.ch/>

swipe, then click a link and then swipe again...

**Comment by Kolos0071** [comment]
Hi! Have same problem in some mobile browsers. I have a bottomsheet and if i act with it, but dont close, it breaks events. Problem on Android Mozilla, Chrome.
