### ISSUE TITLE
Can not chain Vue's event modifiers

### ISSUE THREAD

**Issue by sp00x** [jerrybendy/vue-touch-events#12]
I tried using the built-in Vue event modifiers (https://vuejs.org/v2/guide/events.html#Event-Modifiers) with this, e.g. `<span v-touch.prevent="touchHandler">Tap Me</span>` but that does not seem to work.

I had this in a modal to dismiss it, but the touch event carries through to the thing that was behind my modal and clicks on it also in the process. I had to manually add `event.preventDefault()` in the `touchHandler()` method instead..

Is this something that could be addressed somehow?

**Comment by jerrybendy** [comment]
Event modifiers are not fully support in current version, and it will be coming soon  :)

**Comment by dgirgenti** [comment]
`.prevent` and `.stop` are available as of 1.1.1
