### ISSUE TITLE
Get x and y of touch

### ISSUE THREAD

**Issue by 20chix** [jerrybendy/vue-touch-events#15]
If I have a div 100x100 how can I get the position of where the user has touched?

**Comment by jerrybendy** [comment]
There is no support for getting original touch position currently.

**Comment by 20chix** [comment]
Closing issue, thanks for reply

**Comment by jerrybendy** [comment]
You're welcome

**Comment by SreeChandan** [comment]
any update on this?

**Comment by jerrybendy** [comment]
@SreeChandan  You can update to the latest version, and using `start`, `end` and `moving` events to get the original touch or mouse events. For example:

```html
<div v-touch:start="onStart"></div>
```

```js
export default {
  methods: {
    onStart(event) {
      // Event could be a mouse event or a touch event, it depends your device
      console.log(event)  
    }
  }
}
```
