### ISSUE TITLE
Improvement : Add support for multi clicks and multi taps

### ISSUE THREAD

**Issue by spyesx** [jerrybendy/vue-touch-events#16]
Hello!

I came across your repo while looking for a double tap support. Well, vue-touch-events doesn't support this feature but I found the project good enough to drop a message about that.

Double click is a native browser event now so it won't be hard I guess.
https://developer.mozilla.org/en-US/docs/Web/Events/dblclick

Double tap might require a bit more work. While thinking about that, it would be even better if we could pass the number of taps we want to listen to.

Something like the following for example:
```html
<span v-touch:multitaps="{handler:twoTapsHandler, taps:2}">double tap me</span>
<span v-touch:multitaps="{handler:threeTapsHandler, taps:3}">tap me 3 times</span>
```

**Comment by jerrybendy** [comment]
I don't thing the `multitap` event is very useful for most of people. I'd like keeping this library as light weight as possible, so I don't want to add too many features for it.

**Comment by spyesx** [comment]
I understand. Double click isn't a too fancy feature since double click is already part of most browsers.

For those looking for double (or multiple) tap, I found [vue-touch](https://github.com/vuejs/vue-touch) and their `registerCustomEvent`. It isn't as light unfortunately but it does what I and certainly many others need.
