### ISSUE TITLE
Tap is being triggered on other input elements

### ISSUE THREAD

**Issue by dallincoons** [jerrybendy/vue-touch-events#17]
`<input type="text" @keyup="doSomething()" v-touch:tap="doSomething()">`

This works fine when you're only using this particular input element, but the catch is that `doSomething()` is being triggered on ever other input element on the page?. I'm not using any extra configuration options, just the defaults. Is this a bug or am I doing something wrong?

**Comment by jerrybendy** [comment]
`v-touch` is not similar as `v-on`, you can only pass a function to it. So the correct usage is `v-touch:tap="doSomething">` (without brackets)
