### ISSUE TITLE
Error in description

### ISSUE THREAD

**Issue by vanstolyaroff** [jerrybendy/vue-touch-events#2]
https://www.npmjs.com/package/vue2-touch-events#usage

```
<!-- only when swipe left can trigger the callback -->
<span v-touch:swpie.left="swipeHandler">Swipe Here</span>
```
in 
swpie.left

Spent 2 hours finding error in copy paste :)

**Comment by jerrybendy** [comment]
What's wrong ? 🤔

**Comment by vanstolyaroff** [comment]
It's written "swpie" instead of "swipe" 🙂

С уважением,
Иван Столяров.

**Comment by jerrybendy** [comment]
Oh~ I'm too careless ... I'll fix it soon. Thanks  🙂

**Comment by zezic** [comment]
It's better to make a new release, because description at npm still contain mistype.

**Comment by jerrybendy** [comment]
Sorry, I forgot it.

A new version `v0.2.1` has been published  😊
