### ISSUE TITLE
Does disableClick work?

### ISSUE THREAD

**Issue by Offlein** [jerrybendy/vue-touch-events#20]
Hi, I'm using 1.0.0, and I have a component set up like this. Template:

```
<div class="thing"
         v-on:click="clickHandler"
         v-touch="touchHandler"
    >
```

And Script:
```
{
  name: 'Thing',
  ...
  methods: {
    touchHandler () {
      console.log('Was touched')
    },
    clickHandler () {
      console.log('Was clicked')
    }
  }
}
```

And Vue2TouchEvents is loaded like so:
```
Vue.use(Vue2TouchEvents, {
  disableClick: true,
  touchClass: 'touchActive'
})
```

But whenever I touch, my console logs both "was touched" and "was clicked". Shouldn't disableClick mean that doesn't happen?

I'd like my interface to require one tap to "hover" on the item, and then another tap to "activate" it. On a PC, mouse hover and click would correspond.

I was thinking I could work around this by using a click handler and a touch handler, but if click is always called no matter what, that makes this a bigger hassle. :(

Not sure if I'm doing something wrong, though!

**Comment by jerrybendy** [comment]
Hi,

By default, when you bind a `tap` event, it will do 2 things: bind touch events on mobile devices and bind click event on PC. `tap` event is compatible with both mobile and PC at same time. So you needn't write another `v-on:click` for your components.

The option `disableClick` means that the `tap` event will only bind on mobile, it's helpful if you would use your website on mobile devices only.

**Comment by Offlein** [comment]
Hey Jerry, thanks very much. I think I see my mistake, then!
