### ISSUE TITLE
Improvement : Add support for tapDown and tapUp

### ISSUE THREAD

**Issue by Fragilem17** [jerrybendy/vue-touch-events#23]
Would be great to have a working replacement for @mouseDown and @mouseUp vue events on mobile.

**Comment by Fragilem17** [comment]
I've added a pull request, named the events start and end

**Comment by jerrybendy** [comment]
Thanks for your contribution. I'm very glad to merge your PR 😝

**Comment by Fragilem17** [comment]
It's ready to be pulled, however i would like to improve it where if you swipe outside of the DOM element it also registers as a end event. currently you can have a start without an end if you do that and that should not be possible in my opinion.
