### ISSUE TITLE
fast swiping not working

### ISSUE THREAD

**Issue by vana-dev** [jerrybendy/vue-touch-events#25]
I use "v-touch: swipe.left" and "v-touch: swipe.right" everything works fine, when i swipe slow, or normal speed, but when i try to swipe fast nothing happens: /

**Comment by jerrybendy** [comment]
I tried on my device and it worked well. Swipe has an option `swipeTolerance`, and default value is 30px. It means, if you swipe to right but your finger offset to top or bottom over 30px, the `swipe` event would not be triggered.
