### ISSUE TITLE
Live Sync

### ISSUE THREAD

**Issue by RompeNuca** [jerrybendy/vue-touch-events#27]
I'm using the library, it's very good!
There is a function that would be very helpful,
I want to execute a method the number of times the target moves (I want to animate in real time), currently I can only execute a method when the swipe action ends.
Thank you in advance.

PS: if it exists and I did not find her sorry for this post!

**Comment by RompeNuca** [comment]
I do not work with moving.
I am experimenting in this example:
[link](https://codesandbox.io/s/jz2nz68x35)

If you want to take a look, I think this function is worth it, in many occasions it is rare to have to wait to let go of the screen finger for something to happen.

**Comment by Jones-S** [comment]
I have a similar thing where I want to animate the item which should swipe from top to bottom. First it should follow the finger movement and then after a certain threshold I want to swipe a view completely.

```
movingHandler(e) {
      this.position =  e.targetTouches[0].screenY)
}
```
(Is this the right way to implement the `moving` event where I want to the element to be in sync with the finger?)

I am currently using the `moving` event which is neat. But I also need to reset the position after a user lifts his finger.

I thought, well perfect, there is the `v-touch:end`  – but this does not trigger as a _swipe-end_. It triggers only after lifting the finger when tapping.

Is there something like a `moving-stopped-event` that triggers once a `moving` event has ended?

Thank you for your input.
Cheers

**Comment by Jones-S** [comment]
Oh sorry, no I understand.
I went through:
https://github.com/Fragilem17/vue-touch-events/blob/3f771f8f229a230de4dd3ad35a501d50930a61d4/index.js#L106

And I see that if in my case at the end I get a swipe event trigger.
So I can use `v-touch:swipe.bottom="resetPosition"` to reset the position after the the user stopped moving the item.

**Comment by jerrybendy** [comment]
@Jones-S  `swipe` event is triggered when touch end. `start` and `end` events are supported.

> I thought, well perfect, there is the `v-touch:end` – but this does not trigger as a _swipe-end_. It triggers only after lifting the finger when tapping.
>
> Is there something like a `moving-stopped-event` that triggers once a `moving` event has ended?

I'm not understand this. Can you say something detail?

**Comment by Jones-S** [comment]
I know. As I wrote in my second post, I understood that the `swipe` is triggered anyway. It's all good. Thank you.
My `moving-stopped-event` is exactly the `swipe` event. so it is what I was looking for.

**Comment by jerrybendy** [comment]
@Jones-S No！ `swipe` does not trigger anyway. There is a `swipeTolerance` option. Only you moving your finger in one direction and in `swipeTolerance` px, `swipe` event would be triggered.

**Comment by Jones-S** [comment]
Oh alright. Good to know.

**Comment by cepm-nate** [comment]
So what is the preferred method of detecting a v-touch:moving end (person lifts finger from screen)?

v-touch:end is not fired when moving is done, and v-touch:moved fires once after a threashold is passed, but not when the person's finger is lifted.

**Comment by jerrybendy** [comment]
There was something wrong with the `end` event. I have fixed this issue and now the `end` event can trigger correctly. Just update this dependence to `^2.0.0` version.
