### ISSUE TITLE
No swipe event triggered if finger swipes above another DOM element/Swipe changes direction?

### ISSUE THREAD

**Issue by Jones-S** [jerrybendy/vue-touch-events#29]
I have the following problem:
I use the `moving` event to update a drag-touch movement, where I have an item that can be dragged on screen. When released – on `v-touch:swipe` – I move the dragged/swiped item fully into view if a certain threshold is reached. If not I let it snap back to its original position.

Now if I swipe it, it mostly works, but sometimes my finger swipes over another DOM element – Or maybe it is because I slighty change the swipe direction:
I don't get a swipe event triggered and therefor I would just end up with an item dragged into screen halfway and it would either go back to its position or swipe fully into view.
I would need a proper event for anytime a user removes the finger from screen.

Is this maybe a known issue, or did I miss out on some event I could use?

**Comment by jerrybendy** [comment]
In your case, I think using this library would make your code more complex. IMO, using the native touch events or dray-and-drop library is better.

**Comment by Jones-S** [comment]
Ok. Thanks.
