### ISSUE TITLE
how to ues this plugin in nuxt?

### ISSUE THREAD

**Issue by Caoyiii** [jerrybendy/vue-touch-events#32]

**Comment by jerrybendy** [comment]
an... I never use this in nuxt 😔 If you know how to use it, please comment under this issue 😅

**Comment by karambafe** [comment]
[Nuxt.js plugins](https://nuxtjs.org/guide/plugins#codefund_ad)

1. Create file **vue-touch.js** in plugins folder:
```
import Vue from 'vue';
import Vue2TouchEvents from 'vue2-touch-events';

Vue.use(Vue2TouchEvents);
```

2. Update nuxt.config.js
```
export default {
  plugins: [
    { src: '~/plugins/vue-touch', ssr: false },
  ],
};
```
