### ISSUE TITLE
No "end" event being triggered after "moving" event.

### ISSUE THREAD

**Issue by cepm-nate** [jerrybendy/vue-touch-events#33]
I'm using ```v-touch:moving``` to show a slider-of-sorts, but am having a hard time detecting when the finger is lifted from the screen, as ```v-touch:end``` is not fired. The comment at https://github.com/jerrybendy/vue-touch-events/pull/24#issuecomment-447272454 hints that ```end``` might be of use in my case, but I'm having trouble. Can anyone detect an ```end``` after ```moving```?

Looking at https://github.com/Fragilem17/vue-touch-events/blob/3f771f8f229a230de4dd3ad35a501d50930a61d4/index.js#L113, it looks like it's impossible for the ```end``` event to fire from a native ```touchend``` when ```$this.touchMoved=true``` (only swipe events are triggered), but I could be reading it wrong.

**Comment by jerrybendy** [comment]
Yep, the code here has a mistake. Now, the `end` event only be triggered when `touchMoved` is `false`. I'll fix it soon, but this is a broken change which is not compatible with current version.

```js
            if (!$this.touchMoved) {
                // detect if this is a longTap event or not
                if ($this.callbacks.longtap && event.timeStamp - $this.touchStartTime > options.longTapTimeInterval) {
                    event.preventDefault()
                    triggerEvent(event, this, 'longtap')

                } else {
                    // emit tap event
                    triggerEvent(event, this, 'tap')
                }
                triggerEvent(event, this, 'end')

            }
```

**Comment by jerrybendy** [comment]
I fixed this bug and pushed to the `master` branch.  https://github.com/jerrybendy/vue-touch-events/commit/bae67a7b14dc3cdd84e69c777f25649e38e6164b

I will release a new major version when #31 has been fixed.

**Comment by cepm-nate** [comment]
Awesome, thanks so much for the quick response!

**Comment by jerrybendy** [comment]
@cepm-nate The newest version `v2.0.0` has released. This version has some break changes. you can fellow https://github.com/jerrybendy/vue-touch-events/releases/tag/v2.0.0 to see the detail. 😀
