### ISSUE TITLE
Long press?

### ISSUE THREAD

**Issue by bichikim** [jerrybendy/vue-touch-events#35]
Hi~
Thank you for your module. It saves my time.

I need a Long press event
Do you have a plan to add this new feature

**Comment by jerrybendy** [comment]
Did you mean `longtap` ?

**Comment by bichikim** [comment]
long press ; triggering without a mouse up event

**Comment by bichikim** [comment]
refer to: https://quasar-framework.org/components/touch-hold.html

**Comment by jerrybendy** [comment]
`Quasar`'s `touch-hold` has an modifier `noMouse` to avoid mouse event.  I can't make sure, do you mean that, trigger `longtap` event when finger touch and hold on the screen only (no mouse event)?

**Comment by bichikim** [comment]
It means create to a new long press event that is triggered when a finger or a mouse point touch and hold on the screen for a few seconds without taking the finger off the  screen

**Comment by jerrybendy** [comment]
I got your point. But do you think it is very useful to add a new `longpress` event?

**Comment by bichikim** [comment]
in my opinion most `longpress` actions are used in mobile phones. so it is useful

**Comment by Suprevo** [comment]
Is it so that longtap only triggers on release of the touch/mouse? 
I am looking for a function where a 1 second press triggers an action.

**Comment by jerrybendy** [comment]
You are right. Long press event on a mobile is always touch-hold. I think the `longtap` event is useless now.

I'm planning to add a new long press event, maybe I will call it `touchhold` too. And the `longtap` event would be removed in the next major version.

**Comment by daymerfillad** [comment]
@jerrybendy I also wait for this new function

**Comment by jerrybendy** [comment]
I have added `touchhold` event to the latest version. Please upgrade to `v2.1.0` to experience it 😂 If you have any problems, please let me know
