### ISSUE TITLE
Mouse event in Chrome

### ISSUE THREAD

**Issue by bayssmekanique** [jerrybendy/vue-touch-events#37]
This is more of an FYI for anyone that might come across it in the future and might be a good addition to the documentation.

When using `v-touch:start` and `v-touch:end` events for long touches, a "touch and hold" of close to 500ms (couldn't figure out the exact timing) will cause Chrome to fire a follow-up mouse event.  This was causing my buttons to "stick" because the button would activate and deactivate on the touch events, and then reactivate on the following mouse event.

The way to prevent this is to call `preventDefault()` on the `event` passed into the `v-touch:end` method.
```ts
  touchEnd (event?: TouchEvent) {
    if (event) {
      event.preventDefault()
    }
  }
```

**Comment by jerrybendy** [comment]
The latest version has a `touchhold` event presented, maybe can resolve your issue.
