### ISSUE TITLE
Attach event using addEventListener

### ISSUE THREAD

**Issue by jsinhSolanki** [jerrybendy/vue-touch-events#38]
Hi,
Thanks for this plugin. I am using component framework. And it's create child div of particular component.
So, problem is as those div created inside component is created by framework. And As per my knowledge I can only attach events by.
```
<div v-touch:swipe.right="swipeRightHandler" class="swipe-area" />
```
But how can attach event using refs and access my element.
Currently element I want to attach event is at..
```
const sidebarEl = this.$refs.mainSidebar.$el.childNodes[1];
```
I want to attach event to this sidebarEl element.
~ Thanks

**Comment by jerrybendy** [comment]
Hi,

I think what you want to do is like this:

```
this.$refs.mainSidebar.$el.childNodes[1].addEventListener('touchstart', function(){})
```

And it's a pity that you can't do this by using this directive.  😔

**Comment by jsinhSolanki** [comment]
Hello @jerrybendy ,
Thanks for quick response. I am not good with touch events. After logging this event's event it only gives points and other stuff.
How can I know if user swiped left or right??

**Comment by jerrybendy** [comment]
I just do a little things to detect `swipe` events. If a finger touches on the screen, you would get a `touches` array in the event object. The `touches` array includes the position your finger touched at. Save the position in a variable.

When touch end, you can get a position your finger leaves on the screen. To judge if the X of end position less or greater than the start position, you will know it's swipe left or right.

**Comment by jsinhSolanki** [comment]
Thank you so much.
