### ISSUE TITLE
Error is thrown when touchClass is not set

### ISSUE THREAD

**Issue by stsvilik** [jerrybendy/vue-touch-events#4]
Chrome throws an error whenever `$el.classList.add` is called with an empty value. You must add logic which does not update `classList` if touchClass is not set (or empty).

**Comment by dexluce** [comment]
I think I have the same issue. 

> Uncaught DOMException: Failed to execute 'add' on 'DOMTokenList': The token provided must not be empty.
    at addTouchClass (webpack-internal:///74:148:31)
    at HTMLSpanElement.mouseEnterEvent (webpack-internal:///74:115:17)

The directive is uses like that:
```
<div id="app">
    <b-container id="mainContainer" ref="mainContainer" :class="{onTransition: onTransition}" v-touch:touch="swipeController" v-on:wheel="wheelController">
      <div></div>
      <transition :name="transitionName" mode="out-in">
        <router-view></router-view>
      </transition>
    </b-container>
  </div>
```

Did I do something wrong?

**Comment by stsvilik** [comment]
@dexluce No you did not. This code use DOM native classList.add method to set the class on the element, but this method does not take empty string as a value. Unfortunately touchClass which t attempts to set is empty by default. Its a bug :)

**Comment by dexluce** [comment]
@stsvilik I see. By any chances, any solutions in mind to detect a swipe on mobile?

**Comment by jerrybendy** [comment]
Actually, it is a bug. Maybe I should detect whether the class name exists or try to use another way.

**Comment by jerrybendy** [comment]
I have added a logic on `classList.add`, please upgrade to `v0.2.2` to get the fixed version.
