### ISSUE TITLE
no use methods in an inline JavaScript statement

### ISSUE THREAD

**Issue by zhishan33** [jerrybendy/vue-touch-events#43]
v-touch="handleLogin('params')"
传递参数就直接调用了，不支持内联语法如：<button v-on:click="say('hi')">Say hi</button>

**Comment by jerrybendy** [comment]
Because `v-touch` is a directive, not a `v-on` event. 

You can refer to https://github.com/jerrybendy/vue-touch-events#how-to-add-extra-parameters or #3 to get more details.
