### ISSUE TITLE
Touch Moving Safari

### ISSUE THREAD

**Issue by ngmiduc** [jerrybendy/vue-touch-events#44]
Safari 13.0.1 (14608.2.11.1.11)

Hi,

somehow, when I test my stuff on Safari in dev mode and responsive mode (iphone)
Touch moving event is triggered all the time when I just hover over the div. Is that normal ? Or is this just on safari browser and on IOS safari it will be correct ?

best

**Comment by jerrybendy** [comment]
Hi, It's normal. 

When your finger touches on the screen, the `start` event is triggered, And when you move your finger, the `move` event is triggered.

**Comment by ngmiduc** [comment]
I am sorry, true !
I got confused that Safari desktop doesnt have touch events.

But another issue:
I am running a web app in IOS simulator, and the v-touch:moving handler doesn't get fired when I am dragging the element. When I drag stuff in Chrome it works but in the IOS simulation it doesn't - I didn't test it on a real phone.
