### ISSUE TITLE
Method automatically triggering on page load without click

### ISSUE THREAD

**Issue by SirHodlington** [jerrybendy/vue-touch-events#45]
Unlike @click="cancelUpdate(resetOnCancel)"
the following would automatically trigger the method without clicking when the page loads:
v-touch:tap="cancelUpdate(resetOnCancel)"

Is there a way to use methods with parameters or do I need to avoid them in general?

**Comment by jerrybendy** [comment]
This is a known issue mentioned in README:  https://github.com/jerrybendy/vue-touch-events#how-to-add-extra-parameters

**Comment by SirHodlington** [comment]
Thank you. The problem I had with that was, that it wouldn't let me access other methods with this. from that function. 
I found a different solution that works for me. In case somebody else needs it here it is:

v-touch:tap="(direction, $event) => onClickPlusButton($event)"
v-touch:swipe="(direction, $event) => onClickPlusButton($event, direction)"

**Comment by SirHodlington** [comment]
Some more lessonss-learned if anyone is still readying this.

This will now work:
 v-touch:tap="(variable1, variable2) =>
            myMethod({
              val1: variable1, val: variable2
            })"

This will work:
 v-touch:tap="() =>
            myMethod({
              val1: this.variable1, val: this.variable2
            })"
