### ISSUE TITLE
Infinite loop on touch

### ISSUE THREAD

**Issue by michaelpumo** [jerrybendy/vue-touch-events#47]
If I have an element with a touch event that I need to pass arguments to, it creates an infinite loop and crashes the browser (sometimes).

`<li v-touch:start="abc(xyz)" />`

The above will cause problems.

`<li v-touch:start="abc" />`

The above works...but I need to pass an argument into the function I am calling. How could I do that? I don't see in the docs anywhere with it being used this way.

I'm not sure if this is a bug or just misuse on my part and expected behaviour.

**Comment by jerrybendy** [comment]
Hi,

This is a known issue and has mentioned in README:  https://github.com/jerrybendy/vue-touch-events#how-to-add-extra-parameters

**Comment by michaelpumo** [comment]
Thank you for that. It solves the issue I was having. I somehow did not see this in the README. Feel free to close this issue and have a lovely day!

**Comment by SuharshTyagii** [comment]
> Hi,
> 
> This is a known issue and has mentioned in README: https://github.com/jerrybendy/vue-touch-events#how-to-add-extra-parameters

But inside the return function, I'm not being able to manipulate the data() properties in vue. How can I make it work, please help.

**Comment by jerrybendy** [comment]
@SuharshTyagii  You can use arrow function instead, or make `this` as a variable before `return`.

**Comment by SuharshTyagii** [comment]
Thank you! Used the arrow function instead and it worked.
