### ISSUE TITLE
touchhold/longtap bindings

### ISSUE THREAD

**Issue by lidorkook** [jerrybendy/vue-touch-events#50]
Hey,
I'm using both touchhold and longtap bindings on my app and I saw you're planning to deprecate this feature.
Is there any plan to implement a 'touchholdrelease' binding?
I'm using it when a touchhold event is triggered to pause a video and when a longtap event (when your finger is released) is triggered to play it again.

**Comment by jerrybendy** [comment]
Hi,
I think it could be better if you use `start` and `end` instead for complex conditions. Neither `touchhold` nor `longtap` can not support all conditions. Of cause, `longtap` can be keeped if it's truly useful.
