### ISSUE TITLE
Non global config

### ISSUE THREAD

**Issue by nolimitdev** [jerrybendy/vue-touch-events#52]
Hi, is it possible to override global config? E.g. I would like to use sometimes short distance swipe with default `tapTolerance = 10` but sometimes I need to use long distance swipe e.g. `tapTolerance = 300`. It seems that there is only one option item that support inline configuration per element... `touchClass` => `v-touch-class`. I have tested similarly `v-tap-tolerance` or `v-touch-tap-tolerance` but it does not work.

**Comment by jerrybendy** [comment]
Hi, global configuration overriding is  not supported yet.

**Comment by nolimitdev** [comment]
See PR https://github.com/jerrybendy/vue-touch-events/pull/53 What about you? Is it possible to merge please?

**Comment by jerrybendy** [comment]
Hi, the constructor of `VueTouchEvents` has many options, not only `swipeTolerance`. So I think add a directive for `Tolerance` only is not a good idea.

I think, it would be better to add an `option` parameter to the handlers to override default options. Like below: 

```js
<span
     v-touch:tap="{handler: tapHandler, options: {swipeTolerance: 10, tapTolerance: 10}}"
>Tap</span>
```

**Comment by nolimitdev** [comment]
Ok, I will use so far my forked version in my project. I'm looking forward to use options in future as you suggested.

**Comment by jerrybendy** [comment]
`v2.2.0` has been released. The usage changes to using `v-touch-options` to customize configuration for specified component.

```html
<span v-touch-options="{swipeTolerance: 10}">something</span>
```

**Comment by nolimitdev** [comment]
Hi, there is a little bug in v2.2.0. See PR https://github.com/jerrybendy/vue-touch-events/pull/54

**Comment by jerrybendy** [comment]
Thanks for your PR. I have merged it and release a new version `v2.2.1`. 😄

**Comment by breslauer** [comment]
(Sorry for my english) I think the implementation is not good. For me the idea `I think, it would be better to add an option parameter to the handlers to override default options.` was better. Right now if you want to change disableClick option (in my project disableClick is true in global options) it could not work, cause you change options later than add event listener for our element. In developer version you can define v-touch-options first and it will work, but in production mode it could be tricky. 

works: 
`    v-touch-options="{ disableClick: false }"
    v-touch:swipe.left="handleSwipe"`

doesn't work: 
`    v-touch:swipe.left="handleSwipe"
    v-touch-options="{ disableClick: false }"`

**Comment by jerrybendy** [comment]
Hi  @breslauer ,

My English is not good either. The problem you said is really an issue. The `v-touch` directive doesn't know the overwirted value of `disableClick` when binding events. This causes this issue. Do you have any advice to solve this?
