### ISSUE TITLE
How to disable touch conditionally

### ISSUE THREAD

**Issue by blauweb** [jerrybendy/vue-touch-events#59]
As stated in the topic - there seems no disabled option to exist.
Disabling the button in HTML does not work.

**Comment by jerrybendy** [comment]
You can do it yourself in your touch event callback:

```js
{
  touchHandler() {
    if (this.isButtonDisabled) {
      return;
    }

    // do something
  }
}

```

**Comment by jerrybendy** [comment]
I will close this issue. If you have any questions, feel free to open a new one.
