### ISSUE TITLE
touch moving left and right

### ISSUE THREAD

**Issue by jringbox** [jerrybendy/vue-touch-events#60]
The "v-touch:start / v-touch:end / v-touch:moving" appears to only work for up and down.  Is there support for right and left or is there a combination of other touches that would accomplish this?

In my case, I have a menu I want to slide from the right.  I noticed that most mobile menus you can hold your finger on the touch screen while move right and then left and the menu is only shown by as much as your finger moves.  My thought is that v-touch would have to do a moving event with right and left action.

Also, I was considering later to do a list where the entries in the list could be swiped left or right which I would also exhibit the same behavior with doing a moving left and right which will show a new card for the right or left action to be performed on the row.

I really need a moving left and right that would really show the user has control on the interface and the action to be performed rather than just swiping left or right.

Let me know if I missed how this could be done with the current action events.

**Comment by jerrybendy** [comment]
`start`, `end` and `moving` events are like native `touchstart`, `touchmove` and `touchend` events. You can use these events to customize your actions, both top-bottom and left-right. `moving` event never controls the direction, is there something wrong with your code?

**Comment by jringbox** [comment]
I think from the documentation, I don't understand how to use it.  touchmove says to use this for movement, start and end are used when it starts and stops for the move.  But start and stop and associated with mousedown and mouseup.  So, where is right and left?

**Comment by jerrybendy** [comment]
In your case, you should use `start`, `moving` and `end` at the same time. 

* When `start` triggered, save the position where your finger on, and set a flag to identify that the touch event is started . 
* When `moving` triggered, check the touch starting flag, calculate the move direction and distance to update the UI to show or hide your menu.
* When `end`, clear the flag.

**Comment by jringbox** [comment]
I almost have it.  There's a problem with context on the `end`.  If the mouse is pressed for `start`, in the context of the element on the screen but the mouse event is released outside of the element, `end` never gets called.  How do I deal with this?

**Comment by jerrybendy** [comment]
In fact, I don't have a good idea to resolve this problem. One way to workaround is binding the `end` event on a parent element, maybe parent, maybe grandparent, and maybe even `body`. Thus you can capture the `end` event correctly. I know it's not a good idea, but I don't have better.

**Comment by jringbox** [comment]
I think I have all the scenarios all figured out.  I had to have everything run in the mobile emulator to really see how the TouchEvent object works.  Apparently, when you leave or let go your finger, `end` always gets called.  So, it's not an issue.  Thanks for all the help you have given.

**Comment by jerrybendy** [comment]
The problem is if you leave your finger from an element which doesn't bind `end` event, the `end` event wouldn't be triggered as expected.

**Comment by jringbox** [comment]
Wow, the responsiveness is terrible though for `moving` on my mobile device.  Emulator was fine but a real mobile device has a bit of delay.  Any settings I can tweak to improve this?  I think it's making too many calls to update my menu position.

**Comment by jerrybendy** [comment]
I can't reproduce your issue without any code. The `moving` event would not be triggered very frequently, so I can't make sure what happens.

**Comment by jringbox** [comment]
I added a tolerance logic to the `start` handler I wrote such that changes less than 20 pixels are ignore.  That made the the interface decently responsive.  I can always adjust if I need to.

**Comment by jerrybendy** [comment]
Good job 👍
