### ISSUE TITLE
Support for pan, pinch, rotate?

### ISSUE THREAD

**Issue by priyankakodali94** [jerrybendy/vue-touch-events#62]
Will there be any support for other gestures like pan, pinch and rotate?
The deprecated vue-touch library seems to have support for pan gesture.
It would be great if these could be supported.

**Comment by jerrybendy** [comment]
This library keeps simple and small, so there is no plan to add complex events

**Comment by juan-carvajal** [comment]
I think swipe may be an essential event to support.

**Comment by jerrybendy** [comment]
@juan-carvajal  Yep. And `swipe` has been supported since the first version.
