### ISSUE TITLE
Question: swipe tolerance

### ISSUE THREAD

**Issue by Waaflee** [jerrybendy/vue-touch-events#63]
What it is and how it works? I need to reduce "sensitivity" to swipe as I'm working on a website whose navigation it's entirely controlled with this library (gesture based navigation), and sometimes things get a little messy when a not so "perfect" gesture it's done and  undesired events are fired.

**Comment by jerrybendy** [comment]
About swipe tolerance, for example, if you want to bind a swipe event which specified the direction is `left`, tolerance is 30px. I just draw a simple picture to show it.

![image](https://user-images.githubusercontent.com/7897384/80119504-5c78fc00-85bc-11ea-859c-3f25fb9a7547.png)

**Comment by Waaflee** [comment]
Awesome, thanks you so really much. Fantastically didactic picture there, I
will try this then.

**Comment by jerrybendy** [comment]
That's ok. I will close this issue now, if you have other problems, feel free to open a new one.
