### ISSUE TITLE
Touchenter equivalent

### ISSUE THREAD

**Issue by katymariehughes** [jerrybendy/vue-touch-events#68]
Hi! Thanks for a great tool!

I have a table with two columns. I want to be able to mousedown on one td (in the 2nd col), mouseenter into other tds (in the 2nd col), mouseup and have the tds I hovered over to be 'selected'. 

This works great with v-touch:start, @mouseenter and v-touch:end on desktop, but on mobile the mouseenter does not work. v-touch:moving only fires on the initial td, no others. 

On desktop I get the touchclass applied to the tds, so I had hoped to utilise that, but the touchclass is not applied in mobile. the touchclass is only applied to the single, first clicked td.

Thanks so much for any input!

**Comment by jerrybendy** [comment]
Hi,

I have an idea, but I don't know whether it works. You can bind `v-touch` events on the parent element, such as `table`, then you can get the `td` by `event.target`.  For example:

```html
<table v-touch:moving="onMoving">
  <tr>
    <td>1</td>
    <td>2</td>
    <td>3</td>
  </tr>
  <tr>
    <td>4</td>
    <td>5</td>
    <td>6</td>
  </tr>
</table>
```
```js
{
  methods: {
    onMoving(event) {
      console.log(event.target)
    }
  }
}
```
 
I think you are writing the effect like Excel cell selection. It's not an easy thing to make everything works perfect, Maybe my idea can help you, I can't make sure.
