### ISSUE TITLE
Vue.use(Vue2TouchEvents) is undefined

### ISSUE THREAD

**Issue by dippas** [jerrybendy/vue-touch-events#70]
I had to change this `Vue.use(Vue2TouchEvents)`  as you have in your readme.md to `Vue.use(vueTouchEvents)` because in your index.js you export `vueTouchEvents`

![image](https://user-images.githubusercontent.com/10220287/85278241-9495a180-b47c-11ea-8e68-3241b69647dd.png)

**Comment by jerrybendy** [comment]
Can you give me an example of your code?  

If you use vue without webpack or other build tools, you don't need to write `Vue.use` . If you use webpack, it's not important vueTouchEvents or vue2TouchEvents.

**Comment by dippas** [comment]
I'm not using VUE.js as application per say (`.vue` extension files, nor components/templates, etc),  but using VUE.js as part of a website, so any vue code goes into a normal JS file, but it works as it was an application.

I'm using gulpjs for task runner

Here is a basic example of the code I'm using with your plugin

```
Vue.use(vueTouchEvents)
new Vue({
    el: '.example',
    data: {
        show: 0,
        example: []
    },

    methods: {
        getJson() {
            fetch('example.json')
                .then(response => response.json())
                .then(data => this.example = data)
        },

        swipeTabs(dir) {
            if (dir === 'left' && this.show < document.querySelectorAll('.example-item').length - 1)
                this.show++

            if (dir === 'right' && this.show > 0) 
                this.show--
        }
    },

    created() {
        this.getJson()
    }
})

```

**Comment by dippas** [comment]
Yes you are correct. Maybe some update/info on that on the readme file? Thanks.

**Comment by jerrybendy** [comment]
Thanks for your advice. I will add some tips in the README.
