### ISSUE TITLE
Using `v-touch` in Vue render function

### ISSUE THREAD

**Issue by justice47** [jerrybendy/vue-touch-events#71]
How can we use `v-touch` bindings in [Vue render function](https://vuejs.org/v2/guide/render-function.html)?  
Vue render function have [data object](https://vuejs.org/v2/guide/render-function.html#The-Data-Object-In-Depth) which can be provided. Can we bind `v-touch` handlers through it?

**Comment by jerrybendy** [comment]
Refer to https://vuejs.org/v2/guide/render-function.html

There is something about render function.

**Comment by justice47** [comment]
Thank you for duplicating link to an official documentation! :)

Think I must specify my question -
as which data object property we should provide `v-touch` bindings?

`props`, `attrs`, `directives`, or some other?

**Comment by justice47** [comment]
Managed to do it like so:
```
directives: [
          {
            name: 'touch',
            value: this.nextSlide,
            arg: 'swipe',
            modifiers: {
              left: true
            }
          }
```

**Comment by jerrybendy** [comment]
Maybe I got your point. There is a plan to do so, but I don't have enough time recently.  It could be  very very good to have a PR now 😂  PR welcome 😅
