### ISSUE TITLE
undefined is not an object (evaluating 'r.callbacks')

### ISSUE THREAD

**Issue by nwaughachukwuma** [jerrybendy/vue-touch-events#73]
Hi @jerrybendy we just got an `undefined is not an object (evaluating 'r.callbacks')` error notification on Sentry pointing to line 200

```
if (callbacks.length === 0) {
  return null;
}
for (var i = 0; i < callbacks.length; i++) {
var binding = callbacks[i];  // <-- line 200
if (binding.modifiers.stop) {
    e.stopPropagation();
}
```
Please what could the issue be and is there something I could do to help resolve this?

**Comment by jerrybendy** [comment]
Can you provide something detail? such as your code, browser version, which version of this library you are using, and so on.

**Comment by nwaughachukwuma** [comment]
Ok @jerrybendy, please find the following:

- Lib Version: 2.2.1
- Device: iPhone
- os iOS 14.0
- Browser: Mobile Safari 14.0
- code (stripped to the barest for insight): 
```ts
export default Vue.extend({
  inheritAttrs: false,

  data() {
    return {}
  },
  methods: {
    onTouchStart() {},
    onTouchEnd() {},
    doSomething(index: number) {}
  }
})
```
```html
<div
    v-touch:start="onTouchStart"
    v-touch:end="onTouchEnd"
  >
    <div
      :key="index"
      v-for="(n, index) in obj"
      :style="{
        'left': doSomething(index),
      }"
    >
      <div
        :style="{ backgroundImage: `url(${spriteSrc})` }"
      ></div>
    </div>
  </div>
```

**Comment by jerrybendy** [comment]
Through your code, I can't make sure what happened. Maybe this issue is caused by [L194](https://github.com/jerrybendy/vue-touch-events/blob/5745871771b12fb1c35c327619cbdf1dbc843dd4/index.js#L194) 

```js
var callbacks = $this.callbacks[eventType] || [];
```

If `$el.$$touchObj` is undefined, this issue would be caused. But the `$$touchObj` is bound in L262, which in `v-touch`'s `bind` function. It couldn't be failed.  So, I can't make sure this issue.

**Comment by nwaughachukwuma** [comment]
Ok cool, thanks for taking a stab at it. I should say that this doesn't happen often but we needed to be sure what the issue was. 

I'll inspect further and see if I can reproduce this, so I can update this issue with my findings.

Thanks.
