### ISSUE TITLE
Not working in production

### ISSUE THREAD

**Issue by TCM-dev** [jerrybendy/vue-touch-events#78]
This is the first time I am using this library.
I am using Nuxt so I imported it with a plugin :

_vue-touch.js_
```
import Vue from 'vue'
import Vue2TouchEvents from 'vue2-touch-events'

Vue.use(Vue2TouchEvents)
```

_nuxt.config.js_
`plugins: [{ src: '~/plugins/vue-touch', ssr: false }],`

I also tried with and without :
```
  build: {
    vendor: ['vue-touch']
  }
```
in the same config file

It's working exactly as intended in development, but once I deploy the project to Vercel it does nothing, no error in console, just nothing, it does not execute the functions.

That's how I used it in my components : 
`v-touch="close"` on a div
`v-touch:swipe.right="open"` on the nuxt component in a layout
`v-touch:swipe.left="close"` on another div

Is that a misconfiguration on my side ?

**Comment by jerrybendy** [comment]
I can't make sure. I didn't test this library in SSR environment.

**Comment by TCM-dev** [comment]
This IS actually full static environment, with nuxt generate, also tested with nuxt build && nuxt export

**Comment by sts-ryan-holton** [comment]
@TCM-dev Are you getting an error in the console? I was getting an **intervention** error as described here: https://github.com/jerrybendy/vue-touch-events/issues/77 which was recently added because my events are very similar and had just stopped working, also running on a static environment with `nuxt generate`

**Comment by jerrybendy** [comment]
Thanks for replying. I do really not familiar with nuxt. I can do nothing about this issue 😅

**Comment by TCM-dev** [comment]
Problem solved 2 days ago but I could not find the time to write it.
My project uses vuetify, which already has a touch directive, but your library somehow override it in developement but not in production. Your library is better but I don't know how to remove the directives from vuetify.

**Comment by aner87** [comment]
Hey @TCM-dev sorry I am having the exact same problem.
Could you please be more specific about how you solved it ?

**Comment by TCM-dev** [comment]
As I said in the last comment, I could not solve it and stayed with the vuetify directive, there are probably ways around it but I don't know any of them

**Comment by jerrybendy** [comment]
The conflict with vuetify is solved. You can try to upgrade to the latest version, and add a `namespace` parameter to `Vue.use()`.  Read [this](https://github.com/jerrybendy/vue-touch-events#how-to-resolve-conflict-with-vuetify) for details.

**Comment by aner87** [comment]
OMG thank you so much, I totally missed this part of the github page!
So after I assign a custom namespace, do I have to call vue-touch-events' methods differently?

**Comment by jerrybendy** [comment]
This is my fault. The new version has released for a month, but I forgot to push the commits to GitHub.

And, you are right. When you assign a new namespace, for example, `namespace: 'kiss'`, and now you can use `v-kiss:tap` instead of `v-touch:tap`.

**Comment by Den2016** [comment]
> for example, namespace: 'kiss', and now you can use v-kiss:tap instead of v-touch:tap

please, add this example in documentation.

**Comment by jerrybendy** [comment]
@Den2016  OK. Added.
