### ISSUE TITLE
Add long-touch event

### ISSUE THREAD

**Issue by yehosef** [jerrybendy/vue-touch-events#8]
First - thanks for this! Amazingly simple and effective library.

Is there a way (or could there be) to do a long touch event?

**Comment by jerrybendy** [comment]
Maybe it's useful, and what features do you want? 😉

**Comment by yehosef** [comment]
It's always valuable to have more possibilities available like those from https://github.com/mlyknown/vue-gesture or hammer.js - but I don't know how complicated that is and I don't need it now.

**Comment by jerrybendy** [comment]
Anyway, I want this library to keep simple, but add more features always makes it more useful.

Refer to `vue-gesture`, I think some features such as `longTap` and `doubleTap` are useful. Maybe `doubleTap` would have conflicts with `tap`, and I'll try my best to implement it.

**Comment by yehosef** [comment]
Thanks!  - I agree that it's better to keep simple

**Comment by jerrybendy** [comment]
Added `longtap` event  870dc7adf55e8a1bdf8c2c6a1ec132ffb91ee84b

**Comment by jerrybendy** [comment]
This library is already stable, so I changed the version into `v1.0.0` and published it.

**Comment by yehosef** [comment]
Great -thanks!
