### ISSUE TITLE
Drag & Swipe to change page

### ISSUE THREAD

**Issue by sts-ryan-holton** [jerrybendy/vue-touch-events#87]
In many mobile apps a user is able to essentially "drag & swipe" to navigate to a different page, I've tried using the swipe directive in this package and it seems that I have to be very precise at dragging in an exact horizontal pattern, whereas in many apps I can simply drag from the side of the screen, even at a horizontal angle and have it change the page, but only as I'm dragging and letting go.

Is there a way to produce similar results with this library, if so, what's the closest example and settings to achieve this?

**Comment by jerrybendy** [comment]
The `swipe` event is only a simple implementation. In your case, you have to handle the events by yourself. If you use this library, you can try `v-touch:start / v-touch:end / v-touch:moving` ([documents here](https://github.com/jerrybendy/vue-touch-events#v-touchstart--v-touchend--v-touchmoving)).
