### ISSUE TITLE
How can we use it with external js and normal vue instance?

### ISSUE THREAD

**Issue by hkmsadek** [jerrybendy/vue-touch-events#95]
Hi there, I am running vue.js like jquery in html with vue instance. In wordpress widget, i cannot make it like a pure vue project as I have to use html php and vue all together. So how can I use this as a normal external js file and use the component? Thank you

**Comment by jerrybendy** [comment]
See the usage part. https://github.com/jerrybendy/vue-touch-events#usage

```html
<script src="path/to/vue.js"></script>
<script src="path/to/vue-touch-events.js"></script>
```

The directives will automatically installed and used.

**Comment by hkmsadek** [comment]
Where to get the `vue-touch-events.js` file? Any cdn?

**Comment by jerrybendy** [comment]
Download the `index.js` in this repo. (https://github.com/jerrybendy/vue-touch-events/blob/master/index.js) and put it in your web directory or CDN.
