### ISSUE TITLE
How set a global configuration if vue is used in UMD way (script tag)?

### ISSUE THREAD

**Issue by mrogin-technic** [jerrybendy/vue-touch-events#96]
How set a global configuration if vue is used in UMD way (script tag)?

If I do it as described in the documentation [APIs -> Global configuration (optional)],
neither `Vue.use(Vue2TouchEvents, {...` nor `Vue.use(vueTouchEvents, {...` works.

**Comment by mrogin-technic** [comment]
Too bad it is not supported.
I have now tested swap
```
<script src="path/to/vue.js"></script>
<script src="path/to/vue-touch-events.js"></script>
```
to
```
<script src="path/to/vue-touch-events.js"></script>
<script src="path/to/vue.js"></script>
```
And then I can set the global configuration with
```
	window.vueTouchEvents = vueTouchEvents;
	Vue.use(vueTouchEvents, {
		touchClass: 'active2',
		tapTolerance: 40,
		touchHoldTolerance: 800,
	});
```
So far, everything seems to be working fine this way.
Are there any problems to be expected by this swap of vue.js and vue-touch-events.js?

**Comment by jerrybendy** [comment]
Nice try 😂

With the last part the `index.js`,

```js
if (typeof module === 'object') {
    module.exports = vueTouchEvents;

} else if (typeof define === 'function' && define.amd) {
    define([], function () {
        return vueTouchEvents;
    });
} else if (window.Vue) {
    window.vueTouchEvents = vueTouchEvents;
    Vue.use(vueTouchEvents);
}
```

`window.Vue` is `undefined` when these code be executed. So `vueTouchEvents` is not init in this way.

Your code could work well, good idea 👍

**Comment by mrogin-technic** [comment]
Exactly these last 4 lines from index.js gave me this idea to try it that way. Thanks for the feedback, in that case I will continue to use/test it that way.
