### ISSUE TITLE
Recreating a "slide" gesture

### ISSUE THREAD

**Issue by udit99** [jerrybendy/vue-touch-events#98]
Hi
I'm trying to create a slide gesture using this library where, given an array of buttons, the user long taps on one and then slides his finger across the array to highlight them. Something along the lines of the behavior on a sliding keyboard where the keys pop out when you slide from one key to another. 

1. How would you recommend going about it? I assume something along [these](https://github.com/jerrybendy/vue-touch-events/issues/60#issuecomment-609832054) lines ?
2. I dont see any documentation for what params are passed to the moving handler to be able to tell the location. Easy enough to figure out with a debugger on a desktop based library but not quite easy to do that on mobile :) 

Thanks

**Comment by jerrybendy** [comment]
Hi,

I forgot the parameters of `start` and `moving` events. The paramter is the native mouse or touch event.

The way to get the position of event triggered like below:

```js
function touchX(event) {
    if(event.type.indexOf('mouse') !== -1){
        return event.clientX;
    }
    return event.touches[0].clientX;
}
```

**Comment by udit99** [comment]
That was really helpful, thank you! What I'm running into now is that the movingHandler on the "moving" event stops firing after being dragged for a bit (half a second and about 50-100 pixels or so). Does this ring a bell? If not, I can try and recreate it in a demo

**Comment by jerrybendy** [comment]
It's better to create a demo. I can't understand you very clearly. And, what is _ring a bell_??

**Comment by udit99** [comment]
no worries, I'll create a demo. ["Ring a Bell"](https://dictionary.cambridge.org/us/dictionary/english/ring-a-bell): To sound familiar

**Comment by jerrybendy** [comment]
Is this issue resolved?
